# Generated by Django 2.2.8 on 2020-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20200417_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
