# Generated by Django 2.2.8 on 2020-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20200417_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='parent_post',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(),
        ),
    ]
