# Generated by Django 2.2.8 on 2020-04-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20200417_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='post',
            new_name='parent_post',
        ),
    ]
